name: gyucheol
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - dav1d=1.2.1
  - fontconfig=2.15.0
  - freetype=2.14.1
  - giflib=5.2.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.2
  - jpeg=9e
  - lame=3.100
  - ld_impl_linux-64=2.44
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.7.7
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libiconv=1.18
  - libogg=1.3.5
  - libopus=1.6.1
  - libpng=1.6.54
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtheora=1.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - ncurses=6.5
  - ninja=1.13.2
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pcre2=10.46
  - pixman=0.46.4
  - pthread-stubs=0.3
  - python=3.8.20
  - readline=8.3
  - setuptools=75.1.0
  - sqlite=3.51.1
  - tesseract=5.2.0
  - tk=8.6.15
  - wheel=0.44.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - amfm-decompy==1.0.12.2
      - antlr4-python3-runtime==4.8
      - audioread==3.0.1
      - av==12.3.0
      - bitarray==3.8.0
      - certifi==2026.1.4
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.2.4
      - decorator==5.2.1
      - fairseq==0.12.2
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - future==1.0.0
      - google-auth==2.47.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - hydra-core==1.0.7
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - librosa==0.8.1
      - llvmlite==0.41.1
      - lxml==6.0.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - omegaconf==2.0.6
      - opencv-python==4.5.4.60
      - packaging==25.0
      - pillow==10.4.0
      - pip==24.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - portalocker==3.0.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-speech-features==0.6
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - six==1.17.0
      - soundfile==0.13.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - zipp==3.20.2
prefix: /home/2022113135/.conda/envs/gyucheol
